/* Las tres lecturas de una palabra.

   El glosario daba una definicion y ya. Estas cuatro palabras aguantan
   tres, y son tres registros distintos a proposito:

     now       «Como se vive». Lo que significa hoy, con un ejemplo de la
               vida que ya vives. Aqui el fondo teologico va de contrabando:
               no se nombra, se enseña.
     history   «De donde viene». El origen de la palabra, su campo semantico
               y sus matices. Es el registro profesional, con la cita.
     theology  «Lo que es». Directo y sin contrabando. Es la lectura mas
               corta a proposito — quien llega hasta aqui no necesita rodeos,
               y es la unica que lleva el sello.

   Van en su propio fichero y no dentro de TERMS porque son doce textos
   largos en cinco idiomas: metidos alli, la ficha de cada palabra —su
   alfabeto, su fuente, sus formas— dejaba de poder leerse de un vistazo.
   El guion las busca por el id de la palabra; una palabra sin entrada aqui
   sigue funcionando como siempre, con su definicion de un parrafo.

   LAS CITAS. Cada tarjeta lleva UNA como mucho, la que aporta el numero
   Strong. El aparato entero vive al pie de la hoja, que es donde se
   consulta; repetirlo tres veces por palabra no daba mas rigor, daba mas
   ruido. */

/* La palabra en una palabra. Es lo que va detras del nombre, como en el
   mini-logo: אֱמֶת · Emet · Verdad */
export const GLOSS = {
  emet:  { es: 'Verdad',        en: 'Truth',        pt: 'Verdade',       fr: 'Vérité',        it: 'Verità' },
  ahava: { es: 'Amor',          en: 'Love',         pt: 'Amor',          fr: 'Amour',         it: 'Amore' },
  rhema: { es: 'Palabra dicha', en: 'Spoken word',  pt: 'Palavra dita',  fr: 'Parole dite',   it: 'Parola detta' },
  agape: { es: 'Amor que da',   en: 'Love that gives', pt: 'Amor que dá', fr: 'Amour qui donne', it: 'Amore che dona' }
};

export const CARDS = {
  /* ---------------------------------------------------------- */
  emet: {
    now: {
      es: 'En un mundo de filtros y copy-paste, emet es la verdad que no necesita trucos: como una app que te muestra el error en vez de esconderlo y te dice cómo arreglarlo. No es solo «datos correctos»: es una palabra —o una persona— que sostiene del principio al final, y por eso genera confianza real. El hebreo la dibuja con la primera, la del medio y la última letra del alfabeto: principio, proceso y fin. Si le quitas la primera, queda met, «muerto»: una verdad a medias que ya no vive. En tu feed, emet se siente cuando alguien admite un fallo y lo corrige en público.',
      en: 'In a world of filters and copy-paste, emet is the truth that needs no tricks: like an app that shows you the error instead of hiding it, and tells you how to fix it. It is not just “correct data”: it is a word — or a person — that holds from beginning to end, and that is why it earns real trust. Hebrew draws it with the first, middle and last letters of the alphabet: beginning, process and end. Take the first away and met remains, “dead”: a half-truth that no longer lives. In your feed, emet is what you feel when someone admits a mistake and corrects it in public.',
      pt: 'Num mundo de filtros e copy-paste, emet é a verdade que não precisa de truques: como uma app que te mostra o erro em vez de o esconder e te diz como o resolver. Não é só «dados corretos»: é uma palavra — ou uma pessoa — que sustenta do princípio ao fim, e por isso gera confiança real. O hebraico desenha-a com a primeira, a do meio e a última letra do alfabeto: princípio, processo e fim. Se lhe tirares a primeira, resta met, «morto»: uma verdade a meias que já não vive. No teu feed, emet sente-se quando alguém admite uma falha e a corrige em público.',
      fr: 'Dans un monde de filtres et de copier-coller, emet est la vérité qui n’a besoin d’aucun tour de passe-passe : comme une appli qui vous montre l’erreur au lieu de la cacher, et vous dit comment la réparer. Ce ne sont pas seulement des « données exactes » : c’est une parole — ou une personne — qui tient du début à la fin, et c’est pour cela qu’elle inspire une vraie confiance. L’hébreu la dessine avec la première, la médiane et la dernière lettre de l’alphabet : début, processus et fin. Ôtez la première et il reste met, « mort » : une demi-vérité qui ne vit plus. Dans votre fil, emet se sent quand quelqu’un reconnaît une erreur et la corrige en public.',
      it: 'In un mondo di filtri e copia-incolla, emet è la verità che non ha bisogno di trucchi: come un’app che ti mostra l’errore invece di nasconderlo e ti dice come sistemarlo. Non sono solo «dati corretti»: è una parola — o una persona — che regge dal principio alla fine, ed è per questo che genera fiducia vera. L’ebraico la disegna con la prima, la centrale e l’ultima lettera dell’alfabeto: principio, processo e fine. Togli la prima e resta met, «morto»: una mezza verità che non vive più. Nel tuo feed, emet si sente quando qualcuno ammette un errore e lo corregge in pubblico.'
    },
    history: {
      es: 'Emet (אֱמֶת) es el término hebreo clásico para «verdad», contraído de la raíz אמן, la misma de «amén». Su campo semántico es firmeza, estabilidad y fidelidad más que simple exactitud (Strong H571; la King James la traduce «verdad» 92 veces, y casi todas las demás «verdadero», «fiel» o «seguro»). La raíz une la confiabilidad en contextos de pacto con cumplir la palabra dada, así que emet califica tanto enunciados verdaderos como personas fiables (Brown et al., 1906, H571). La grafía álef-mem-tav —primera, del medio y última letra de un alfabeto de 22— es un dato real de posición que la tradición judía lee como símbolo de totalidad. Esa lectura no es parte del léxico: pertenece a la lectura más honda, al final de este libro.',
      en: 'Emet (אֱמֶת) is the classical Hebrew term for “truth”, contracted from the root אמן — the same root behind “amen”. Its semantic field is firmness, stability and faithfulness rather than mere accuracy (Strong’s H571; the King James renders it “truth” 92 times, and most of the rest “true”, “faithful” or “sure”). The root ties reliability in covenant contexts to keeping one’s word, so emet qualifies both true statements and trustworthy people (Brown et al., 1906, H571). The alef-mem-tav spelling — first, middle and last letters of a 22-letter alphabet — is a real positional fact that Jewish tradition reads as a symbol of totality. That reading is not part of the lexicon: it belongs to the deeper reading, at the end of this book.',
      pt: 'Emet (אֱמֶת) é o termo hebraico clássico para «verdade», contraído da raiz אמן, a mesma de «ámen». O seu campo semântico é firmeza, estabilidade e fidelidade mais do que simples exatidão (Strong H571; a King James tradu-la «verdade» 92 vezes, e quase todas as outras «verdadeiro», «fiel» ou «seguro»). A raiz une a confiabilidade em contextos de aliança ao cumprimento da palavra dada, pelo que emet qualifica tanto enunciados verdadeiros como pessoas fiáveis (Brown et al., 1906, H571). A grafia álef-mem-tav — primeira, do meio e última letra de um alfabeto de 22 — é um dado real de posição que a tradição judaica lê como símbolo de totalidade. Essa leitura não faz parte do léxico: pertence à leitura mais funda, no fim deste livro.',
      fr: 'Emet (אֱמֶת) est le terme hébreu classique pour « vérité », contracté de la racine אמן — celle d’« amen ». Son champ sémantique est la fermeté, la stabilité et la fidélité plus que la simple exactitude (Strong H571 ; la King James le rend par « vérité » 92 fois, et presque tout le reste par « vrai », « fidèle » ou « sûr »). La racine lie la fiabilité, dans les contextes d’alliance, au fait de tenir parole : emet qualifie donc aussi bien des énoncés vrais que des personnes dignes de confiance (Brown et al., 1906, H571). La graphie alef-mem-tav — première, médiane et dernière lettre d’un alphabet de 22 — est un fait de position réel que la tradition juive lit comme un symbole de totalité. Cette lecture ne fait pas partie du lexique : elle appartient à la lecture plus profonde, à la fin de ce livre.',
      it: 'Emet (אֱמֶת) è il termine ebraico classico per «verità», contratto dalla radice אמן, la stessa di «amen». Il suo campo semantico è fermezza, stabilità e fedeltà più che semplice esattezza (Strong H571; la King James lo rende «verità» 92 volte, e quasi tutte le altre «vero», «fedele» o «sicuro»). La radice lega l’affidabilità nei contesti di patto al mantenere la parola data, così emet qualifica tanto enunciati veri quanto persone affidabili (Brown et al., 1906, H571). La grafia alef-mem-tav — prima, centrale e ultima lettera di un alfabeto di 22 — è un dato reale di posizione che la tradizione ebraica legge come simbolo di totalità. Quella lettura non fa parte del lessico: appartiene alla lettura più profonda, alla fine di questo libro.'
    },
    theology: {
      es: 'Emet es verdad confiable: lo que es sólido, fiel y digno de confianza. No es solo no mentir; es ser alguien cuya palabra se cumple del inicio al fin. En la vida real, es el amigo que dice la verdad aunque le cueste y después hace lo que prometió.',
      en: 'Emet is trustworthy truth: what is solid, faithful and worth relying on. It is not merely not lying; it is being someone whose word comes true from start to finish. In real life, it is the friend who tells you the truth even when it costs them, and then does what they promised.',
      pt: 'Emet é verdade confiável: o que é sólido, fiel e digno de confiança. Não é só não mentir; é ser alguém cuja palavra se cumpre do início ao fim. Na vida real, é o amigo que diz a verdade mesmo quando lhe custa e depois faz o que prometeu.',
      fr: 'Emet est une vérité digne de confiance : ce qui est solide, fidèle et sur quoi l’on peut s’appuyer. Ce n’est pas seulement ne pas mentir ; c’est être quelqu’un dont la parole s’accomplit du début à la fin. Dans la vraie vie, c’est l’ami qui dit la vérité même quand cela lui coûte, et qui fait ensuite ce qu’il avait promis.',
      it: 'Emet è verità affidabile: ciò che è solido, fedele e degno di fiducia. Non è soltanto non mentire; è essere qualcuno la cui parola si compie dall’inizio alla fine. Nella vita reale, è l’amico che dice la verità anche quando gli costa e poi fa quello che aveva promesso.'
    }
  },

  /* ---------------------------------------------------------- */
  ahava: {
    now: {
      es: 'Ahavá es amor que se decide más que se siente: como quien defiende a un desconocido del linchamiento aunque le cueste seguidores. No espera «tener ganas»; quiere el bien del otro y actúa por él. El detalle que lo hace interesante: su valor numérico es 13, el mismo de ejad, «uno», como si amar uniera lo que está roto. En digital, ahavá aparece cuando una comunidad modera con empatía: protege al que llega, corrige sin humillar y pone límites claros. Nadie le pone la etiqueta, pero se vive.',
      en: 'Ahavah is love that is decided more than felt: like someone defending a stranger from a pile-on even at the cost of followers. It does not wait to feel like it; it wants the other’s good and acts on it. The detail that makes it interesting: its numerical value is 13, the same as echad, “one”, as if loving joined what is broken. Online, ahavah shows up when a community moderates with empathy: it protects the newcomer, corrects without humiliating, and sets clear limits. Nobody labels it, but it is lived.',
      pt: 'Ahavá é amor que se decide mais do que se sente: como quem defende um desconhecido do linchamento mesmo que lhe custe seguidores. Não espera «ter vontade»; quer o bem do outro e age por ele. O detalhe que o torna interessante: o seu valor numérico é 13, o mesmo de ejad, «um», como se amar unisse o que está partido. No digital, ahavá aparece quando uma comunidade modera com empatia: protege quem chega, corrige sem humilhar e põe limites claros. Ninguém lhe põe a etiqueta, mas vive-se.',
      fr: 'Ahava est un amour qui se décide plus qu’il ne se ressent : comme celui qui défend un inconnu du lynchage même si cela lui coûte des abonnés. Il n’attend pas « d’en avoir envie » ; il veut le bien de l’autre et agit pour lui. Le détail qui le rend intéressant : sa valeur numérique est 13, la même qu’ejad, « un », comme si aimer réunissait ce qui est brisé. En ligne, ahava apparaît quand une communauté modère avec empathie : elle protège celui qui arrive, corrige sans humilier et pose des limites claires. Personne ne lui met d’étiquette, mais cela se vit.',
      it: 'Ahavà è amore che si decide più di quanto si senta: come chi difende uno sconosciuto dal linciaggio anche a costo di perdere follower. Non aspetta «di averne voglia»; vuole il bene dell’altro e agisce per lui. Il dettaglio che lo rende interessante: il suo valore numerico è 13, lo stesso di ejad, «uno», come se amare unisse ciò che è rotto. Nel digitale, ahavà compare quando una comunità modera con empatia: protegge chi arriva, corregge senza umiliare e mette limiti chiari. Nessuno le mette l’etichetta, ma si vive.'
    },
    history: {
      es: 'Ahavah (אַהֲבָה) es el sustantivo femenino de la misma raíz que el verbo ahav, «amar» (Strong H157). En el hebreo bíblico describe un amor de lealtad, elección y pacto, no solo una emoción espontánea. Los dos mandatos centrales usan el verbo, no el sustantivo: «amarás (ve’ahavtá) a YHWH tu Dios» (Deuteronomio 6:5) y «amarás (ve’ahavtá) a tu prójimo como a ti mismo» (Levítico 19:18). Misma raíz, mismo amor de pacto activo: el verbo es el que manda, y el sustantivo ahavá nombra la cualidad que ese verbo pone en obra. La tradición judía ha señalado su guematría, 13, igual a la de ejad, «uno», como indicio simbólico de unidad en el acto de amar (Brown et al., 1906, H160).',
      en: 'Ahavah (אַהֲבָה) is the feminine noun built on the same root as the verb ahav, “to love” (Strong’s H157). In biblical Hebrew it describes a love of loyalty, election and covenant, not only a spontaneous emotion. The two central commands use the verb, not the noun: “you shall love (ve’ahavta) YHWH your God” (Deuteronomy 6:5) and “you shall love (ve’ahavta) your neighbour as yourself” (Leviticus 19:18). Same root, same active covenant love: the verb does the commanding, and the noun ahavah names the quality that verb puts into practice. Jewish tradition has noted its gematria, 13, matching that of echad, “one”, as a symbolic hint of unity in the act of loving (Brown et al., 1906, H160).',
      pt: 'Ahavah (אַהֲבָה) é o substantivo feminino da mesma raiz que o verbo ahav, «amar» (Strong H157). No hebraico bíblico descreve um amor de lealdade, eleição e aliança, não só uma emoção espontânea. Os dois mandamentos centrais usam o verbo, não o substantivo: «amarás (ve’ahavtá) YHWH teu Deus» (Deuteronómio 6:5) e «amarás (ve’ahavtá) o teu próximo como a ti mesmo» (Levítico 19:18). Mesma raiz, mesmo amor de aliança ativo: é o verbo que manda, e o substantivo ahavá nomeia a qualidade que esse verbo põe em prática. A tradição judaica assinalou a sua guematria, 13, igual à de ejad, «um», como indício simbólico de unidade no ato de amar (Brown et al., 1906, H160).',
      fr: 'Ahavah (אַהֲבָה) est le nom féminin formé sur la même racine que le verbe ahav, « aimer » (Strong H157). En hébreu biblique, il décrit un amour de loyauté, d’élection et d’alliance, pas seulement une émotion spontanée. Les deux commandements centraux emploient le verbe, non le nom : « tu aimeras (ve’ahavta) YHWH ton Dieu » (Deutéronome 6:5) et « tu aimeras (ve’ahavta) ton prochain comme toi-même » (Lévitique 19:18). Même racine, même amour d’alliance actif : c’est le verbe qui commande, et le nom ahava nomme la qualité que ce verbe met en œuvre. La tradition juive a relevé sa guématrie, 13, identique à celle d’ejad, « un », comme indice symbolique d’unité dans l’acte d’aimer (Brown et al., 1906, H160).',
      it: 'Ahavah (אַהֲבָה) è il sostantivo femminile della stessa radice del verbo ahav, «amare» (Strong H157). Nell’ebraico biblico descrive un amore di lealtà, elezione e patto, non solo un’emozione spontanea. I due comandi centrali usano il verbo, non il sostantivo: «amerai (ve’ahavtà) YHWH tuo Dio» (Deuteronomio 6:5) e «amerai (ve’ahavtà) il tuo prossimo come te stesso» (Levitico 19:18). Stessa radice, stesso amore di patto attivo: è il verbo a comandare, e il sostantivo ahavà nomina la qualità che quel verbo mette in pratica. La tradizione ebraica ha notato la sua ghematria, 13, uguale a quella di ejad, «uno», come indizio simbolico di unità nell’atto di amare (Brown et al., 1906, H160).'
    },
    theology: {
      es: 'Ahavá es amor decidido: querer y procurar el bien del otro, incluso cuando no hay emoción que lo empuje. En la vida real, es cuidar a un familiar enfermo aunque estés agotado, o tratar bien a quien al principio te cayó mal.',
      en: 'Ahavah is decided love: to want and to work for the other’s good, even when no feeling is pushing you. In real life, it is caring for a sick relative when you are exhausted, or treating well the person you disliked at first.',
      pt: 'Ahavá é amor decidido: querer e procurar o bem do outro, mesmo quando não há emoção que o empurre. Na vida real, é cuidar de um familiar doente ainda que estejas exausto, ou tratar bem quem ao início te caiu mal.',
      fr: 'Ahava est un amour décidé : vouloir et chercher le bien de l’autre, même quand aucune émotion ne vous y pousse. Dans la vraie vie, c’est prendre soin d’un proche malade alors que vous êtes épuisé, ou bien traiter celui qui vous avait d’abord déplu.',
      it: 'Ahavà è amore deciso: volere e procurare il bene dell’altro, anche quando non c’è emozione che lo spinga. Nella vita reale, è prendersi cura di un familiare malato pur essendo sfiniti, o trattare bene chi all’inizio ti stava antipatico.'
    }
  },

  /* ---------------------------------------------------------- */
  rhema: {
    now: {
      es: 'Rhema es la palabra que llega aquí y ahora, para ti: no el mensaje entero, sino la frase concreta que te mueve a actuar. Como esa notificación que aparece justo cuando estás a punto de rendirte: «hoy, solo un paso». En tu día a día puede ser un mensaje de tres líneas —«confío en ti para esto»—: no es un sermón, es una palabra puntual que ordena el caos y te empuja.',
      en: 'Rhema is the word that arrives here and now, for you: not the whole message, but the particular sentence that moves you to act. Like the notification that appears exactly when you are about to give up: “today, just one step”. Day to day it can be a three-line message — “I trust you with this” —: not a sermon, but one timely word that orders the chaos and pushes you.',
      pt: 'Rhema é a palavra que chega aqui e agora, para ti: não a mensagem inteira, mas a frase concreta que te move a agir. Como aquela notificação que aparece mesmo quando estás prestes a desistir: «hoje, só um passo». No teu dia a dia pode ser uma mensagem de três linhas — «confio em ti para isto» —: não é um sermão, é uma palavra pontual que ordena o caos e te empurra.',
      fr: 'Rhèma est la parole qui arrive ici et maintenant, pour vous : non pas le message entier, mais la phrase précise qui vous met en mouvement. Comme cette notification qui apparaît juste au moment où vous alliez abandonner : « aujourd’hui, un seul pas ». Au quotidien, ce peut être trois lignes — « je te fais confiance pour ça » — : pas un sermon, mais une parole ponctuelle qui remet de l’ordre et vous pousse.',
      it: 'Rhema è la parola che arriva qui e ora, per te: non il messaggio intero, ma la frase concreta che ti muove ad agire. Come quella notifica che compare proprio quando stai per mollare: «oggi, solo un passo». Nel quotidiano può essere un messaggio di tre righe — «mi fido di te per questo» —: non è un sermone, è una parola puntuale che mette ordine nel caos e ti spinge.'
    },
    history: {
      es: 'Rhêma (ῥῆμα), en griego clásico y helenístico, denota «lo dicho»: un enunciado concreto (Strong G4487; la King James lo traduce «palabra» 56 veces). Tiende a un dicho específico más que a un discurso largo, y en el Nuevo Testamento suele llevar peso performativo: una palabra recordada, obedecida o que activa la fe (Romanos 10:17, «la fe viene por el oír, y el oír por la rhema de Cristo»). Lo que la enseñanza popular exagera es oponerla limpiamente a logos: «logos es el mensaje entero, rhema es la palabra para ti». La lexicografía de referencia no sostiene una línea tan dura (Bauer et al., 2000): son sinónimos cercanos que se cruzan mucho, y el Nuevo Testamento los usa como intercambiables en varios lugares. Carson (1996) llama a ese paso —tratar una tendencia suave como una frontera fija— una «distinción semántica ilegítima». La tendencia es real; la regla tajante, no.',
      en: 'Rhêma (ῥῆμα), in classical and Hellenistic Greek, denotes “what is said”: a particular utterance (Strong’s G4487; the King James renders it “word” 56 times). It leans toward a specific saying rather than an extended discourse, and in the New Testament it often carries performative weight: a word remembered, obeyed, or one that activates faith (Romans 10:17, “faith comes by hearing, and hearing by the rhema of Christ”). What the popular teaching overstates is a clean opposition to logos: “logos is the whole message, rhema is the word for you”. Standard lexicography does not support so hard a line (Bauer et al., 2000): the two are close synonyms with heavy overlap, and the New Testament uses them interchangeably in several places. Carson (1996) calls this move — treating a soft tendency as a settled boundary — an “illegitimate semantic distinction”. The tendency is real; the sharp rule is not.',
      pt: 'Rhêma (ῥῆμα), no grego clássico e helenístico, denota «o dito»: um enunciado concreto (Strong G4487; a King James tradu-lo «palavra» 56 vezes). Tende para um dito específico mais do que para um discurso longo, e no Novo Testamento costuma levar peso performativo: uma palavra lembrada, obedecida ou que ativa a fé (Romanos 10:17, «a fé vem pelo ouvir, e o ouvir pela rhema de Cristo»). O que o ensino popular exagera é opô-la de forma limpa a logos: «logos é a mensagem inteira, rhema é a palavra para ti». A lexicografia de referência não sustenta uma linha tão dura (Bauer et al., 2000): são sinónimos próximos que se cruzam muito, e o Novo Testamento usa-os como intercambiáveis em vários lugares. Carson (1996) chama a esse passo — tratar uma tendência suave como uma fronteira fixa — uma «distinção semântica ilegítima». A tendência é real; a regra rígida, não.',
      fr: 'Rhêma (ῥῆμα), en grec classique et hellénistique, désigne « ce qui est dit » : un énoncé précis (Strong G4487 ; la King James le rend par « parole » 56 fois). Il tend vers un dire particulier plutôt que vers un long discours, et dans le Nouveau Testament il porte souvent un poids performatif : une parole rappelée, obéie, ou qui suscite la foi (Romains 10:17, « la foi vient de ce qu’on entend, et ce qu’on entend vient de la rhèma du Christ »). Ce que l’enseignement populaire exagère, c’est une opposition nette avec logos : « le logos est le message entier, la rhèma est la parole pour vous ». La lexicographie de référence ne soutient pas une ligne aussi dure (Bauer et al., 2000) : ce sont des synonymes proches qui se recoupent largement, et le Nouveau Testament les emploie l’un pour l’autre à plusieurs endroits. Carson (1996) appelle ce geste — traiter une tendance souple comme une frontière fixe — une « distinction sémantique illégitime ». La tendance est réelle ; la règle tranchée, non.',
      it: 'Rhêma (ῥῆμα), nel greco classico ed ellenistico, denota «ciò che è detto»: un enunciato preciso (Strong G4487; la King James lo rende «parola» 56 volte). Tende a un detto specifico più che a un discorso lungo, e nel Nuovo Testamento porta spesso un peso performativo: una parola ricordata, obbedita o che attiva la fede (Romani 10:17, «la fede viene dall’ascolto, e l’ascolto dalla rhema di Cristo»). Ciò che l’insegnamento popolare esagera è opporla nettamente a logos: «il logos è il messaggio intero, la rhema è la parola per te». La lessicografia di riferimento non sostiene una linea così dura (Bauer et al., 2000): sono sinonimi vicini che si sovrappongono molto, e il Nuovo Testamento li usa in modo intercambiabile in diversi punti. Carson (1996) chiama questo passo — trattare una tendenza morbida come un confine fisso — una «distinzione semantica illegittima». La tendenza è reale; la regola netta, no.'
    },
    theology: {
      es: 'Rhema es palabra dicha y aplicada: un enunciado concreto que se recibe y se obedece aquí y ahora. En la vida real, es la instrucción puntual que cambia tu decisión en el momento en que hay que decidir.',
      en: 'Rhema is a word spoken and applied: a particular utterance received and obeyed here and now. In real life, it is the timely instruction that changes your decision at the moment the decision has to be made.',
      pt: 'Rhema é palavra dita e aplicada: um enunciado concreto que se recebe e se obedece aqui e agora. Na vida real, é a instrução pontual que muda a tua decisão no momento em que há que decidir.',
      fr: 'Rhèma est une parole dite et appliquée : un énoncé concret que l’on reçoit et auquel on obéit ici et maintenant. Dans la vraie vie, c’est l’instruction ponctuelle qui change votre décision au moment où il faut décider.',
      it: 'Rhema è parola detta e applicata: un enunciato concreto che si riceve e si obbedisce qui e ora. Nella vita reale, è l’istruzione puntuale che cambia la tua decisione nel momento in cui bisogna decidere.'
    }
  },

  /* ---------------------------------------------------------- */
  agape: {
    now: {
      es: 'Ágape es amor que da sin exigir nada: como el creador que regala su tiempo para levantar a otro más pequeño, sin pedir crédito. No es amor por conveniencia, es decisión de benevolencia. Lo curioso es que en el Nuevo Testamento agapē aparece por todas partes mientras eros —el amor pasional— no aparece ni una vez: es otra cosa distinta del deseo. En redes se respira cuando una comunidad reúne fondos para alguien en crisis sin convertirlo en tendencia: hay don, y no calcula retorno.',
      en: 'Agape is love that gives without demanding anything: like the creator who gives away their time to lift a smaller channel, without asking for credit. It is not love out of convenience, it is a decision of goodwill. The curious part is that in the New Testament agapē appears everywhere while eros — passionate love — does not appear once: it is something other than desire. Online you can feel it when a community raises funds for someone in crisis without making it trend: there is a gift, and it is not calculating a return.',
      pt: 'Ágape é amor que dá sem exigir nada: como o criador que oferece o seu tempo para levantar outro mais pequeno, sem pedir crédito. Não é amor por conveniência, é decisão de benevolência. O curioso é que no Novo Testamento agapē aparece por todo o lado enquanto eros — o amor passional — não aparece uma única vez: é algo distinto do desejo. Nas redes respira-se quando uma comunidade reúne fundos para alguém em crise sem o transformar em tendência: há dom, e não calcula retorno.',
      fr: 'Agapè est un amour qui donne sans rien exiger : comme le créateur qui offre son temps pour faire monter un plus petit que lui, sans demander de crédit. Ce n’est pas un amour de convenance, c’est une décision de bienveillance. Le curieux, c’est que dans le Nouveau Testament agapē apparaît partout tandis qu’eros — l’amour passionnel — n’apparaît pas une seule fois : c’est autre chose que le désir. En ligne, cela se respire quand une communauté réunit des fonds pour quelqu’un en crise sans en faire une tendance : il y a don, et il ne calcule pas de retour.',
      it: 'Agape è amore che dà senza pretendere nulla: come il creator che regala il proprio tempo per far crescere un canale più piccolo, senza chiedere credito. Non è amore per convenienza, è decisione di benevolenza. La cosa curiosa è che nel Nuovo Testamento agapē compare ovunque mentre eros — l’amore passionale — non compare neppure una volta: è altro rispetto al desiderio. Sui social si respira quando una comunità raccoglie fondi per qualcuno in crisi senza farne una tendenza: c’è dono, e non calcola ritorno.'
    },
    history: {
      es: 'Agapē (ἀγάπη), en el griego del Nuevo Testamento, designa un amor de voluntad y benevolencia, propio de la relación de Dios con el ser humano y de la ética de las primeras comunidades cristianas (Strong G26; la King James lo traduce «amor» 86 veces). En el uso se distingue de eros, el deseo, y de philia, la amistad, y aparece con mucha frecuencia en contextos de don, sacrificio y mandamiento. Eros no aparece ni una vez en todo el Nuevo Testamento griego: su ausencia es una señal tan deliberada como la frecuencia de agapē. La lexicografía destaca su uso para traducir el hebreo ahavah en la Septuaginta, también en Deuteronomio 6:5, y su consolidación como virtud teologal a través del Nuevo Testamento (Bauer et al., 2000, G26).',
      en: 'Agapē (ἀγάπη), in New Testament Greek, denotes a love of will and goodwill, characteristic of God’s relation to human beings and of the ethics of the earliest Christian communities (Strong’s G26; the King James renders it “love” 86 times). In usage it is distinguished from eros, desire, and from philia, friendship, and appears very often in contexts of gift, sacrifice and commandment. Eros does not appear once in the whole Greek New Testament: its absence is as deliberate a signal as agapē’s frequency. Lexicography notes its use to translate Hebrew ahavah in the Septuagint, including Deuteronomy 6:5, and its consolidation as a theological virtue through the New Testament (Bauer et al., 2000, G26).',
      pt: 'Agapē (ἀγάπη), no grego do Novo Testamento, designa um amor de vontade e benevolência, próprio da relação de Deus com o ser humano e da ética das primeiras comunidades cristãs (Strong G26; a King James tradu-lo «amor» 86 vezes). No uso distingue-se de eros, o desejo, e de philia, a amizade, e aparece com muita frequência em contextos de dom, sacrifício e mandamento. Eros não aparece uma única vez em todo o Novo Testamento grego: a sua ausência é um sinal tão deliberado como a frequência de agapē. A lexicografia destaca o seu uso para traduzir o hebraico ahavah na Septuaginta, também em Deuteronómio 6:5, e a sua consolidação como virtude teologal através do Novo Testamento (Bauer et al., 2000, G26).',
      fr: 'Agapē (ἀγάπη), dans le grec du Nouveau Testament, désigne un amour de volonté et de bienveillance, propre à la relation de Dieu avec l’être humain et à l’éthique des premières communautés chrétiennes (Strong G26 ; la King James le rend par « amour » 86 fois). Dans l’usage, il se distingue d’eros, le désir, et de philia, l’amitié, et apparaît très souvent dans des contextes de don, de sacrifice et de commandement. Eros n’apparaît pas une seule fois dans tout le Nouveau Testament grec : son absence est un signal aussi délibéré que la fréquence d’agapē. La lexicographie souligne son emploi pour traduire l’hébreu ahavah dans la Septante, y compris en Deutéronome 6:5, et sa consolidation comme vertu théologale à travers le Nouveau Testament (Bauer et al., 2000, G26).',
      it: 'Agapē (ἀγάπη), nel greco del Nuovo Testamento, designa un amore di volontà e benevolenza, proprio della relazione di Dio con l’essere umano e dell’etica delle prime comunità cristiane (Strong G26; la King James lo rende «amore» 86 volte). Nell’uso si distingue da eros, il desiderio, e da philia, l’amicizia, e compare molto spesso in contesti di dono, sacrificio e comandamento. Eros non compare neppure una volta in tutto il Nuovo Testamento greco: la sua assenza è un segnale deliberato quanto la frequenza di agapē. La lessicografia sottolinea il suo uso per tradurre l’ebraico ahavah nella Settanta, anche in Deuteronomio 6:5, e il suo consolidarsi come virtù teologale attraverso il Nuovo Testamento (Bauer et al., 2000, G26).'
    },
    theology: {
      es: 'Ágape es amor que da sin esperar retorno: la decisión de buscar el bien del otro por benevolencia y no por conveniencia. En la vida real, es ayudar a alguien con su carga aunque no te beneficie, o perdonar sin exigir disculpas.',
      en: 'Agape is love that gives without expecting return: the decision to seek the other’s good out of goodwill and not convenience. In real life, it is helping someone with their load when it does not benefit you, or forgiving without demanding an apology.',
      pt: 'Ágape é amor que dá sem esperar retorno: a decisão de procurar o bem do outro por benevolência e não por conveniência. Na vida real, é ajudar alguém com a sua carga ainda que não te beneficie, ou perdoar sem exigir desculpas.',
      fr: 'Agapè est un amour qui donne sans attendre de retour : la décision de chercher le bien de l’autre par bienveillance et non par convenance. Dans la vraie vie, c’est aider quelqu’un à porter sa charge même sans y gagner, ou pardonner sans exiger d’excuses.',
      it: 'Agape è amore che dà senza attendere ritorno: la decisione di cercare il bene dell’altro per benevolenza e non per convenienza. Nella vita reale, è aiutare qualcuno con il suo carico anche se non ti conviene, o perdonare senza pretendere scuse.'
    }
  }
};
