/* Las tres lecturas de una palabra.

   El glosario daba una definicion y ya. Estas cuatro palabras aguantan
   tres, y son tres registros distintos a proposito:

     now       «Como se vive». Lo que significa hoy, con un ejemplo de la
               vida que ya vives. Aqui el fondo teologico va de contrabando:
               no se nombra, se enseña.
     history   «De donde viene». El origen de la palabra, su campo semantico
               y sus matices. Es el registro profesional, con la cita.
     theology  «Lo que es». Directo y sin contrabando. Es la lectura mas
               corta a proposito — quien llega hasta aqui no necesita rodeos,
               y es la unica que lleva el sello.

   Van en su propio fichero y no dentro de TERMS porque son doce textos
   largos en cinco idiomas: metidos alli, la ficha de cada palabra —su
   alfabeto, su fuente, sus formas— dejaba de poder leerse de un vistazo.
   El guion las busca por el id de la palabra; una palabra sin entrada aqui
   sigue funcionando como siempre, con su definicion de un parrafo.

   LAS CITAS. Cada tarjeta lleva UNA como mucho, la que aporta el numero
   Strong. El aparato entero vive al pie de la hoja, que es donde se
   consulta; repetirlo tres veces por palabra no daba mas rigor, daba mas
   ruido. */

/* La palabra en una palabra. Es lo que va detras del nombre, como en el
   mini-logo: אֱמֶת · Emet · Verdad */
export const GLOSS = {
  emet:  { es: 'Verdad',        en: 'Truth',        pt: 'Verdade',       fr: 'Vérité',        it: 'Verità' },
  ahava: { es: 'Amor',          en: 'Love',         pt: 'Amor',          fr: 'Amour',         it: 'Amore' },
  rhema: { es: 'Palabra dicha', en: 'Spoken word',  pt: 'Palavra dita',  fr: 'Parole dite',   it: 'Parola detta' },
  agape: { es: 'Amor que da',   en: 'Love that gives', pt: 'Amor que dá', fr: 'Amour qui donne', it: 'Amore che dona' }
};

export const CARDS = {
  /* ---------------------------------------------------------- */
  emet: {
    now: {
      es: 'En un mundo de filtros y copy-paste, emet es la verdad que no necesita trucos: como una app que te muestra el error en vez de esconderlo y te dice cómo arreglarlo. No es solo «datos correctos»: es una palabra —o una persona— que sostiene del principio al final, y por eso genera confianza real. El hebreo la dibuja con la primera, la del medio y la última letra del alfabeto: principio, proceso y fin. Si le quitas la primera, queda met, «muerto»: una verdad a medias que ya no vive. En tu feed, emet se siente cuando alguien admite un fallo y lo corrige en público.',
      en: 'In a world of filters and copy-paste, emet is the truth that needs no tricks: like an app that shows you the error instead of hiding it, and tells you how to fix it. It is not just “correct data”: it is a word — or a person — that holds from beginning to end, and that is why it earns real trust. Hebrew draws it with the first, middle and last letters of the alphabet: beginning, process and end. Take the first away and met remains, “dead”: a half-truth that no longer lives. In your feed, emet is what you feel when someone admits a mistake and corrects it in public.',
      pt: 'Num mundo de filtros e copy-paste, emet é a verdade que não precisa de truques: como uma app que te mostra o erro em vez de o esconder e te diz como o resolver. Não é só «dados corretos»: é uma palavra — ou uma pessoa — que sustenta do princípio ao fim, e por isso gera confiança real. O hebraico desenha-a com a primeira, a do meio e a última letra do alfabeto: princípio, processo e fim. Se lhe tirares a primeira, resta met, «morto»: uma verdade a meias que já não vive. No teu feed, emet sente-se quando alguém admite uma falha e a corrige em público.',
      fr: 'Dans un monde de filtres et de copier-coller, emet est la vérité qui n’a besoin d’aucun tour de passe-passe : comme une appli qui vous montre l’erreur au lieu de la cacher, et vous dit comment la réparer. Ce ne sont pas seulement des « données exactes » : c’est une parole — ou une personne — qui tient du début à la fin, et c’est pour cela qu’elle inspire une vraie confiance. L’hébreu la dessine avec la première, la médiane et la dernière lettre de l’alphabet : début, processus et fin. Ôtez la première et il reste met, « mort » : une demi-vérité qui ne vit plus. Dans votre fil, emet se sent quand quelqu’un reconnaît une erreur et la corrige en public.',
      it: 'In un mondo di filtri e copia-incolla, emet è la verità che non ha bisogno di trucchi: come un’app che ti mostra l’errore invece di nasconderlo e ti dice come sistemarlo. Non sono solo «dati corretti»: è una parola — o una persona — che regge dal principio alla fine, ed è per questo che genera fiducia vera. L’ebraico la disegna con la prima, la centrale e l’ultima lettera dell’alfabeto: principio, processo e fine. Togli la prima e resta met, «morto»: una mezza verità che non vive più. Nel tuo feed, emet si sente quando qualcuno ammette un errore e lo corregge in pubblico.'
    },
    history: {
      es: 'Emet (אֱמֶת) es el término hebreo clásico para «verdad», pero su campo semántico incluye firmeza, estabilidad y fidelidad más que mera exactitud proposicional. La grafía —álef, mem, tav— se ha leído tradicionalmente como símbolo de totalidad: la primera, la del medio y la última letra del alfabeto. La raíz se asocia a confiabilidad en contextos de pacto y de palabra dada, de modo que emet califica tanto enunciados verdaderos como caracteres fiables; de ahí que en pasajes clave se traduzca «verdad» o «fidelidad» según el contexto (Brown et al., 1906, H571).',
      en: 'Emet (אֱמֶת) is the classical Hebrew term for “truth”, but its semantic field takes in firmness, stability and faithfulness rather than mere propositional accuracy. The spelling — alef, mem, tav — has traditionally been read as a symbol of totality: the first, middle and last letters of the alphabet. The root is tied to reliability in covenant contexts and in the keeping of one’s word, so emet qualifies true statements and trustworthy characters alike; hence in key passages it is rendered “truth” or “faithfulness” depending on context (Brown et al., 1906, H571).',
      pt: 'Emet (אֱמֶת) é o termo hebraico clássico para «verdade», mas o seu campo semântico inclui firmeza, estabilidade e fidelidade mais do que mera exatidão proposicional. A grafia — álef, mem, tav — foi tradicionalmente lida como símbolo de totalidade: a primeira, a do meio e a última letra do alfabeto. A raiz associa-se a confiabilidade em contextos de pacto e de palavra dada, pelo que emet qualifica tanto enunciados verdadeiros como caracteres fiáveis; daí que em passagens-chave se traduza «verdade» ou «fidelidade» consoante o contexto (Brown et al., 1906, H571).',
      fr: 'Emet (אֱמֶת) est le terme hébreu classique pour « vérité », mais son champ sémantique englobe la fermeté, la stabilité et la fidélité plus que la simple exactitude propositionnelle. La graphie — alef, mem, tav — a traditionnellement été lue comme un symbole de totalité : la première, la médiane et la dernière lettre de l’alphabet. La racine renvoie à la fiabilité dans les contextes d’alliance et de parole donnée, de sorte qu’emet qualifie aussi bien des énoncés vrais que des caractères sûrs ; d’où sa traduction par « vérité » ou « fidélité » selon le contexte (Brown et al., 1906, H571).',
      it: 'Emet (אֱמֶת) è il termine ebraico classico per «verità», ma il suo campo semantico comprende fermezza, stabilità e fedeltà più che semplice esattezza proposizionale. La grafia — alef, mem, tav — è stata tradizionalmente letta come simbolo di totalità: la prima, la centrale e l’ultima lettera dell’alfabeto. La radice si lega all’affidabilità nei contesti di patto e di parola data, cosicché emet qualifica tanto enunciati veri quanto caratteri fidati; da qui la resa con «verità» o «fedeltà» a seconda del contesto (Brown et al., 1906, H571).'
    },
    theology: {
      es: 'Emet es verdad confiable: lo que es sólido, fiel y digno de confianza. No es solo no mentir; es ser alguien cuya palabra se cumple del inicio al fin. En la vida real, es el amigo que dice la verdad aunque le cueste y después hace lo que prometió.',
      en: 'Emet is trustworthy truth: what is solid, faithful and worth relying on. It is not merely not lying; it is being someone whose word comes true from start to finish. In real life, it is the friend who tells you the truth even when it costs them, and then does what they promised.',
      pt: 'Emet é verdade confiável: o que é sólido, fiel e digno de confiança. Não é só não mentir; é ser alguém cuja palavra se cumpre do início ao fim. Na vida real, é o amigo que diz a verdade mesmo quando lhe custa e depois faz o que prometeu.',
      fr: 'Emet est une vérité digne de confiance : ce qui est solide, fidèle et sur quoi l’on peut s’appuyer. Ce n’est pas seulement ne pas mentir ; c’est être quelqu’un dont la parole s’accomplit du début à la fin. Dans la vraie vie, c’est l’ami qui dit la vérité même quand cela lui coûte, et qui fait ensuite ce qu’il avait promis.',
      it: 'Emet è verità affidabile: ciò che è solido, fedele e degno di fiducia. Non è soltanto non mentire; è essere qualcuno la cui parola si compie dall’inizio alla fine. Nella vita reale, è l’amico che dice la verità anche quando gli costa e poi fa quello che aveva promesso.'
    }
  },

  /* ---------------------------------------------------------- */
  ahava: {
    now: {
      es: 'Ahavá es amor que se decide más que se siente: como quien defiende a un desconocido del linchamiento aunque le cueste seguidores. No espera «tener ganas»; quiere el bien del otro y actúa por él. El detalle que lo hace interesante: su valor numérico es 13, el mismo de ejad, «uno», como si amar uniera lo que está roto. En digital, ahavá aparece cuando una comunidad modera con empatía: protege al que llega, corrige sin humillar y pone límites claros. Nadie le pone la etiqueta, pero se vive.',
      en: 'Ahavah is love that is decided more than felt: like someone defending a stranger from a pile-on even at the cost of followers. It does not wait to feel like it; it wants the other’s good and acts on it. The detail that makes it interesting: its numerical value is 13, the same as echad, “one”, as if loving joined what is broken. Online, ahavah shows up when a community moderates with empathy: it protects the newcomer, corrects without humiliating, and sets clear limits. Nobody labels it, but it is lived.',
      pt: 'Ahavá é amor que se decide mais do que se sente: como quem defende um desconhecido do linchamento mesmo que lhe custe seguidores. Não espera «ter vontade»; quer o bem do outro e age por ele. O detalhe que o torna interessante: o seu valor numérico é 13, o mesmo de ejad, «um», como se amar unisse o que está partido. No digital, ahavá aparece quando uma comunidade modera com empatia: protege quem chega, corrige sem humilhar e põe limites claros. Ninguém lhe põe a etiqueta, mas vive-se.',
      fr: 'Ahava est un amour qui se décide plus qu’il ne se ressent : comme celui qui défend un inconnu du lynchage même si cela lui coûte des abonnés. Il n’attend pas « d’en avoir envie » ; il veut le bien de l’autre et agit pour lui. Le détail qui le rend intéressant : sa valeur numérique est 13, la même qu’ejad, « un », comme si aimer réunissait ce qui est brisé. En ligne, ahava apparaît quand une communauté modère avec empathie : elle protège celui qui arrive, corrige sans humilier et pose des limites claires. Personne ne lui met d’étiquette, mais cela se vit.',
      it: 'Ahavà è amore che si decide più di quanto si senta: come chi difende uno sconosciuto dal linciaggio anche a costo di perdere follower. Non aspetta «di averne voglia»; vuole il bene dell’altro e agisce per lui. Il dettaglio che lo rende interessante: il suo valore numerico è 13, lo stesso di ejad, «uno», come se amare unisse ciò che è rotto. Nel digitale, ahavà compare quando una comunità modera con empatia: protegge chi arriva, corregge senza umiliare e mette limiti chiari. Nessuno le mette l’etichetta, ma si vive.'
    },
    history: {
      es: 'Ahavah (אַהֲבָה) es el sustantivo derivado del verbo ahav, «amar», y en el hebreo bíblico describe un amor de lealtad, elección y pacto antes que una emoción espontánea. Aparece en los mandatos centrales —«amarás a YHWH», «amarás a tu prójimo»— y en relaciones de alianza, lo que lo perfila como compromiso activo. La tradición judía ha señalado su guematría, 13, coincidente con la de ejad, «uno», como indicio simbólico de unidad en el acto de amar (Brown et al., 1906, H160).',
      en: 'Ahavah (אַהֲבָה) is the noun derived from the verb ahav, “to love”, and in biblical Hebrew it describes a love of loyalty, election and covenant rather than a spontaneous emotion. It appears in the central commands — “you shall love YHWH”, “you shall love your neighbour” — and in covenant relationships, which frames it as active commitment. Jewish tradition has noted its gematria, 13, matching that of echad, “one”, as a symbolic hint of unity in the act of loving (Brown et al., 1906, H160).',
      pt: 'Ahavah (אַהֲבָה) é o substantivo derivado do verbo ahav, «amar», e no hebraico bíblico descreve um amor de lealdade, eleição e pacto antes de uma emoção espontânea. Aparece nos mandatos centrais — «amarás YHWH», «amarás o teu próximo» — e em relações de aliança, o que o perfila como compromisso ativo. A tradição judaica assinalou a sua guematria, 13, coincidente com a de ejad, «um», como indício simbólico de unidade no ato de amar (Brown et al., 1906, H160).',
      fr: 'Ahavah (אַהֲבָה) est le substantif dérivé du verbe ahav, « aimer », et en hébreu biblique il décrit un amour de loyauté, d’élection et d’alliance plutôt qu’une émotion spontanée. Il apparaît dans les commandements centraux — « tu aimeras YHWH », « tu aimeras ton prochain » — et dans les relations d’alliance, ce qui le dessine comme un engagement actif. La tradition juive a relevé sa guématrie, 13, identique à celle d’ejad, « un », comme indice symbolique d’unité dans l’acte d’aimer (Brown et al., 1906, H160).',
      it: 'Ahavah (אַהֲבָה) è il sostantivo derivato dal verbo ahav, «amare», e nell’ebraico biblico descrive un amore di lealtà, elezione e patto prima che un’emozione spontanea. Compare nei comandi centrali — «amerai YHWH», «amerai il tuo prossimo» — e nelle relazioni di alleanza, il che lo delinea come impegno attivo. La tradizione ebraica ha notato la sua ghematria, 13, coincidente con quella di ejad, «uno», come indizio simbolico di unità nell’atto di amare (Brown et al., 1906, H160).'
    },
    theology: {
      es: 'Ahavá es amor decidido: querer y procurar el bien del otro, incluso cuando no hay emoción que lo empuje. En la vida real, es cuidar a un familiar enfermo aunque estés agotado, o tratar bien a quien al principio te cayó mal.',
      en: 'Ahavah is decided love: to want and to work for the other’s good, even when no feeling is pushing you. In real life, it is caring for a sick relative when you are exhausted, or treating well the person you disliked at first.',
      pt: 'Ahavá é amor decidido: querer e procurar o bem do outro, mesmo quando não há emoção que o empurre. Na vida real, é cuidar de um familiar doente ainda que estejas exausto, ou tratar bem quem ao início te caiu mal.',
      fr: 'Ahava est un amour décidé : vouloir et chercher le bien de l’autre, même quand aucune émotion ne vous y pousse. Dans la vraie vie, c’est prendre soin d’un proche malade alors que vous êtes épuisé, ou bien traiter celui qui vous avait d’abord déplu.',
      it: 'Ahavà è amore deciso: volere e procurare il bene dell’altro, anche quando non c’è emozione che lo spinga. Nella vita reale, è prendersi cura di un familiare malato pur essendo sfiniti, o trattare bene chi all’inizio ti stava antipatico.'
    }
  },

  /* ---------------------------------------------------------- */
  rhema: {
    now: {
      es: 'Rhema es la palabra que llega aquí y ahora, para ti: no el mensaje entero, sino la frase concreta que te mueve a actuar. Como esa notificación que aparece justo cuando estás a punto de rendirte: «hoy, solo un paso». En griego significa «lo dicho», y se distingue de logos, que es el mensaje completo. En tu día a día puede ser un mensaje de tres líneas —«confío en ti para esto»—: no es un sermón, es una palabra puntual que ordena el caos y te empuja.',
      en: 'Rhema is the word that arrives here and now, for you: not the whole message, but the particular sentence that moves you to act. Like the notification that appears exactly when you are about to give up: “today, just one step”. In Greek it means “what is said”, and it is distinguished from logos, the complete message. Day to day it can be a three-line message — “I trust you with this” —: not a sermon, but one timely word that orders the chaos and pushes you.',
      pt: 'Rhema é a palavra que chega aqui e agora, para ti: não a mensagem inteira, mas a frase concreta que te move a agir. Como aquela notificação que aparece mesmo quando estás prestes a desistir: «hoje, só um passo». Em grego significa «o dito», e distingue-se de logos, que é a mensagem completa. No teu dia a dia pode ser uma mensagem de três linhas — «confio em ti para isto» —: não é um sermão, é uma palavra pontual que ordena o caos e te empurra.',
      fr: 'Rhèma est la parole qui arrive ici et maintenant, pour vous : non pas le message entier, mais la phrase précise qui vous met en mouvement. Comme cette notification qui apparaît juste au moment où vous alliez abandonner : « aujourd’hui, un seul pas ». En grec, le mot signifie « ce qui est dit », et il se distingue de logos, le message complet. Au quotidien, ce peut être trois lignes — « je te fais confiance pour ça » — : pas un sermon, mais une parole ponctuelle qui remet de l’ordre et vous pousse.',
      it: 'Rhema è la parola che arriva qui e ora, per te: non il messaggio intero, ma la frase concreta che ti muove ad agire. Come quella notifica che compare proprio quando stai per mollare: «oggi, solo un passo». In greco significa «ciò che è detto», e si distingue da logos, che è il messaggio completo. Nel quotidiano può essere un messaggio di tre righe — «mi fido di te per questo» —: non è un sermone, è una parola puntuale che mette ordine nel caos e ti spinge.'
    },
    history: {
      es: 'Rhêma (ῥῆμα), en griego clásico y helenístico, denota «lo dicho»: un enunciado concreto. En el Nuevo Testamento se emplea para palabras específicas, a menudo con carácter de mandato, promesa o aplicación inmediata, en contraste con logos como mensaje o discurso amplio. La lexicografía neotestamentaria recoge usos en los que rhema funciona como palabra recordada, obedecida o que activa la fe: no una frase cualquiera, sino un enunciado con peso performativo en su contexto (Bauer et al., 2000, G4487).',
      en: 'Rhêma (ῥῆμα), in classical and Hellenistic Greek, denotes “what is said”: a particular utterance. In the New Testament it is used for specific words, often carrying the force of a command, a promise or an immediate application, in contrast with logos as message or extended discourse. New Testament lexicography records uses in which rhema functions as a word remembered, obeyed, or one that activates faith: not just any phrase, but an utterance with performative weight in its context (Bauer et al., 2000, G4487).',
      pt: 'Rhêma (ῥῆμα), no grego clássico e helenístico, denota «o dito»: um enunciado concreto. No Novo Testamento emprega-se para palavras específicas, muitas vezes com carácter de mandato, promessa ou aplicação imediata, em contraste com logos como mensagem ou discurso amplo. A lexicografia neotestamentária recolhe usos em que rhema funciona como palavra recordada, obedecida ou que ativa a fé: não uma frase qualquer, mas um enunciado com peso performativo no seu contexto (Bauer et al., 2000, G4487).',
      fr: 'Rhêma (ῥῆμα), en grec classique et hellénistique, désigne « ce qui est dit » : un énoncé concret. Dans le Nouveau Testament, le mot s’emploie pour des paroles précises, souvent à valeur d’ordre, de promesse ou d’application immédiate, par contraste avec logos comme message ou discours étendu. La lexicographie néotestamentaire relève des emplois où rhèma fonctionne comme parole rappelée, obéie, ou qui suscite la foi : non une phrase quelconque, mais un énoncé au poids performatif dans son contexte (Bauer et al., 2000, G4487).',
      it: 'Rhêma (ῥῆμα), nel greco classico ed ellenistico, denota «ciò che è detto»: un enunciato concreto. Nel Nuovo Testamento si impiega per parole specifiche, spesso con carattere di comando, promessa o applicazione immediata, in contrasto con logos come messaggio o discorso ampio. La lessicografia neotestamentaria registra usi in cui rhema funziona come parola ricordata, obbedita o che attiva la fede: non una frase qualsiasi, ma un enunciato con peso performativo nel suo contesto (Bauer et al., 2000, G4487).'
    },
    theology: {
      es: 'Rhema es palabra dicha y aplicada: un enunciado concreto que se recibe y se obedece aquí y ahora. En la vida real, es la instrucción puntual que cambia tu decisión en el momento en que hay que decidir.',
      en: 'Rhema is a word spoken and applied: a particular utterance received and obeyed here and now. In real life, it is the timely instruction that changes your decision at the moment the decision has to be made.',
      pt: 'Rhema é palavra dita e aplicada: um enunciado concreto que se recebe e se obedece aqui e agora. Na vida real, é a instrução pontual que muda a tua decisão no momento em que há que decidir.',
      fr: 'Rhèma est une parole dite et appliquée : un énoncé concret que l’on reçoit et auquel on obéit ici et maintenant. Dans la vraie vie, c’est l’instruction ponctuelle qui change votre décision au moment où il faut décider.',
      it: 'Rhema è parola detta e applicata: un enunciato concreto che si riceve e si obbedisce qui e ora. Nella vita reale, è l’istruzione puntuale che cambia la tua decisione nel momento in cui bisogna decidere.'
    }
  },

  /* ---------------------------------------------------------- */
  agape: {
    now: {
      es: 'Ágape es amor que da sin exigir nada: como el creador que regala su tiempo para levantar a otro más pequeño, sin pedir crédito. No es amor por conveniencia, es decisión de benevolencia. Lo curioso es que en el Nuevo Testamento agapē aparece por todas partes mientras eros —el amor pasional— no aparece ni una vez: es otra cosa distinta del deseo. En redes se respira cuando una comunidad reúne fondos para alguien en crisis sin convertirlo en tendencia: hay don, y no calcula retorno.',
      en: 'Agape is love that gives without demanding anything: like the creator who gives away their time to lift a smaller channel, without asking for credit. It is not love out of convenience, it is a decision of goodwill. The curious part is that in the New Testament agapē appears everywhere while eros — passionate love — does not appear once: it is something other than desire. Online you can feel it when a community raises funds for someone in crisis without making it trend: there is a gift, and it is not calculating a return.',
      pt: 'Ágape é amor que dá sem exigir nada: como o criador que oferece o seu tempo para levantar outro mais pequeno, sem pedir crédito. Não é amor por conveniência, é decisão de benevolência. O curioso é que no Novo Testamento agapē aparece por todo o lado enquanto eros — o amor passional — não aparece uma única vez: é algo distinto do desejo. Nas redes respira-se quando uma comunidade reúne fundos para alguém em crise sem o transformar em tendência: há dom, e não calcula retorno.',
      fr: 'Agapè est un amour qui donne sans rien exiger : comme le créateur qui offre son temps pour faire monter un plus petit que lui, sans demander de crédit. Ce n’est pas un amour de convenance, c’est une décision de bienveillance. Le curieux, c’est que dans le Nouveau Testament agapē apparaît partout tandis qu’eros — l’amour passionnel — n’apparaît pas une seule fois : c’est autre chose que le désir. En ligne, cela se respire quand une communauté réunit des fonds pour quelqu’un en crise sans en faire une tendance : il y a don, et il ne calcule pas de retour.',
      it: 'Agape è amore che dà senza pretendere nulla: come il creator che regala il proprio tempo per far crescere un canale più piccolo, senza chiedere credito. Non è amore per convenienza, è decisione di benevolenza. La cosa curiosa è che nel Nuovo Testamento agapē compare ovunque mentre eros — l’amore passionale — non compare neppure una volta: è altro rispetto al desiderio. Sui social si respira quando una comunità raccoglie fondi per qualcuno in crisi senza farne una tendenza: c’è dono, e non calcola ritorno.'
    },
    history: {
      es: 'Agapē (ἀγάπη), en el griego del Nuevo Testamento, designa un amor de voluntad y benevolencia, característico de la relación de Dios con el ser humano y de la ética de las primeras comunidades cristianas. Se diferencia de eros, el deseo, y de philia, la amistad, y aparece con alta frecuencia en contextos de don, sacrificio y mandamiento. La lexicografía destaca su uso para traducir ahavah en la Septuaginta y su consolidación como virtud teologal (Bauer et al., 2000, G26).',
      en: 'Agapē (ἀγάπη), in New Testament Greek, denotes a love of will and goodwill, characteristic of God’s relation to human beings and of the ethics of the earliest Christian communities. It is distinguished from eros, desire, and from philia, friendship, and appears with high frequency in contexts of gift, sacrifice and commandment. Lexicography notes its use to translate ahavah in the Septuagint and its consolidation as a theological virtue (Bauer et al., 2000, G26).',
      pt: 'Agapē (ἀγάπη), no grego do Novo Testamento, designa um amor de vontade e benevolência, característico da relação de Deus com o ser humano e da ética das primeiras comunidades cristãs. Diferencia-se de eros, o desejo, e de philia, a amizade, e aparece com alta frequência em contextos de dom, sacrifício e mandamento. A lexicografia destaca o seu uso para traduzir ahavah na Septuaginta e a sua consolidação como virtude teologal (Bauer et al., 2000, G26).',
      fr: 'Agapē (ἀγάπη), dans le grec du Nouveau Testament, désigne un amour de volonté et de bienveillance, caractéristique de la relation de Dieu à l’être humain et de l’éthique des premières communautés chrétiennes. Il se distingue d’eros, le désir, et de philia, l’amitié, et apparaît très fréquemment dans des contextes de don, de sacrifice et de commandement. La lexicographie souligne son emploi pour traduire ahavah dans la Septante et sa consolidation comme vertu théologale (Bauer et al., 2000, G26).',
      it: 'Agapē (ἀγάπη), nel greco del Nuovo Testamento, designa un amore di volontà e benevolenza, caratteristico della relazione di Dio con l’essere umano e dell’etica delle prime comunità cristiane. Si distingue da eros, il desiderio, e da philia, l’amicizia, e compare con alta frequenza in contesti di dono, sacrificio e comandamento. La lessicografia sottolinea il suo uso per tradurre ahavah nella Settanta e il suo consolidarsi come virtù teologale (Bauer et al., 2000, G26).'
    },
    theology: {
      es: 'Ágape es amor que da sin esperar retorno: la decisión de buscar el bien del otro por benevolencia y no por conveniencia. En la vida real, es ayudar a alguien con su carga aunque no te beneficie, o perdonar sin exigir disculpas.',
      en: 'Agape is love that gives without expecting return: the decision to seek the other’s good out of goodwill and not convenience. In real life, it is helping someone with their load when it does not benefit you, or forgiving without demanding an apology.',
      pt: 'Ágape é amor que dá sem esperar retorno: a decisão de procurar o bem do outro por benevolência e não por conveniência. Na vida real, é ajudar alguém com a sua carga ainda que não te beneficie, ou perdoar sem exigir desculpas.',
      fr: 'Agapè est un amour qui donne sans attendre de retour : la décision de chercher le bien de l’autre par bienveillance et non par convenance. Dans la vraie vie, c’est aider quelqu’un à porter sa charge même sans y gagner, ou pardonner sans exiger d’excuses.',
      it: 'Agape è amore che dà senza attendere ritorno: la decisione di cercare il bene dell’altro per benevolenza e non per convenienza. Nella vita reale, è aiutare qualcuno con il suo carico anche se non ti conviene, o perdonare senza pretendere scuse.'
    }
  }
};
